### ISSUE TITLE
How to generate an API token

### ISSUE THREAD

**Issue by IIIAdmin** [jesusmb1995/SlackBackup#1]
Hello Jesus!

Thank you for creating this utility, it is very cool!!!

For me, it wasn't obvious from your video how to create an API token, but wandering around the Slack help center I found this page:

```
             https://api.slack.com/web
```

Once you are a signed-in user, the bottom of this page will give you an opportunity to create a "Test API Token" which works very well with your application.

Cheers!

SC

**Comment by jesusmb1995** [comment]
Thank you for the comment. I'm glad it useful.

Cheers :)

**Comment by jesusmb1995** [comment]
Yes, by now you have to get the token from here: https://api.slack.com/web.

Also If you know a bit of programming, you can create a new utility to get a token using the oAuth system: https://api.slack.com/docs/oauth
